# Generated by Django 2.0 on 2018-01-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareRead', '0002_auto_20180129_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(default='f7f0881c049511e88d8aa0afbd73a24a', max_length=32, verbose_name='编号'),
        ),
    ]
