# Generated by Django 2.0 on 2018-01-29 03:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shareRead', '0005_auto_20180129_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
