# Generated by Django 2.0 on 2018-01-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareRead', '0006_auto_20180129_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateUpdate',
            field=models.DateField(auto_now=True),
        ),
    ]
