# Generated by Django 2.0 on 2018-01-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareRead', '0007_student_dateupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
