# Generated by Django 2.0 on 2018-01-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareRead', '0010_auto_20180129_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'get_latest_by': 'dateUpdate', 'ordering': ['-dateUpdate'], 'verbose_name': '申请者信息', 'verbose_name_plural': '申请者详细信息'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'get_latest_by': 'dateUpdate', 'ordering': ['-dateUpdate'], 'verbose_name': '学生信息', 'verbose_name_plural': '学生详细填写'},
        ),
    ]
