# Generated by Django 2.0.1 on 2018-02-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareRead', '0011_auto_20180129_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='deleteFlag',
            field=models.CharField(default=False, max_length=5, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='student',
            name='deleteFlag',
            field=models.CharField(default=False, max_length=5, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='selectStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shareRead.Student', verbose_name='选择学生'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '待选择'), (1, '已经选择'), (2, '选择成功')], default=0, verbose_name='选择状态'),
        ),
    ]
